# Copyright (c) 2025 Fantom Foundation
#
# Use of this software is governed by the Business Source License included
# in the LICENSE file and at fantom.foundation/bsl11.
#
# Change Date: 2028-4-16
#
# On the date above, in accordance with the Business Source License, use of
# this software will be governed by the GNU Lesser General Public License v3.

skip_without_test: false
skip_with_build_tags: false
json_output: true
silent_mode: false
min_msi: 0.90 # should be >0.95
exclude_dirs:
