# Copyright (c) 2025 Fantom Foundation
#
# Use of this software is governed by the Business Source License included
# in the LICENSE file and at fantom.foundation/bsl11.
#
# Change Date: 2028-4-16
#
# On the date above, in accordance with the Business Source License, use of
# this software will be governed by the GNU Lesser General Public License v3.

language: go

go:
  - 1.13.x

go_import_path: github.com/0xsoniclabs/consensus

cache:
  directories:
    - $GOPATH/pkg

env:
  global:
    - GO111MODULE=on

# install: skip

script:
  - go build -v ./...

after_success:
  - |
    if [ -n "$GO_TEST" ]; then
      go test -coverprofile=coverage.txt -covermode=atomic ./...
    elif [ -n "$GO_INTEGRATION_TEST" ]; then
      go test ./integration/
    fi

after_script:
  - |
    if [ -n "$GO_TEST" ]; then
      bash <(curl -s https://codecov.io/bash)
    fi

matrix:
  include:
    - name: go test
      env:
        - GO_TEST=1

    - name: testnet
      env:
        - GO_INTEGRATION_TEST=1
